### ISSUE TITLE
Does this work yet?

### ISSUE THREAD

**Issue by DRuffer** [sdwood68/YAFFA#1]
I was impressed that you've got some output and terminal echo, but otherwise, it doesn't pass my 1st sniff test, which I always give to Forth systems.

 YAFFA - Yet Another Forth For Arduino, Version 0.6
 Copyright (C) 2012 Stuart Wood
 This program comes with ABSOLUTELY NO WARRANTY.
 This is free software, and you are welcome to
 redistribute it under certain conditions.

 Terminal Echo is On
 Pre-Defined Words : 157
 Input Buffer: Starts at $6B3, Ends at $712
 Token Buffer: Starts at $693, Ends at $6B2
 Forth Space: Starts at $148, Ends at $647
 307 ($133) bytes free

> > words5 .

Note that "words" and "5 ." were entered in separate "sends" on Arduino 1.6.5's Serial Monitor.

What tests do you use?

DaR

**Comment by DRuffer** [comment]
But then, I tried HyperAccess, which is what I've had setup for 328eForth, and things are working fine! ;)

You probably should address the issue with Arduino's Serial Monitor, at some point, but I'm off to try getting BLE running in my coinForth.

Thanks for getting me past my latest brick wall.

Stay tuned to: https://github.com/DRuffer/coinForth

DaR

**Comment by sdwood68** [comment]
DaR, 

Sorry for not noticing your posts. The Arduino Serial Monitor needs to be set up to send Carriage Returns per line. Line Feeds are stripped out.

Stuart

**Comment by DRuffer** [comment]
That worked, thanks!   DaR
