### ISSUE TITLE
Passing longs

### ISSUE THREAD

**Issue by DRuffer** [sdwood68/YAFFA#3]
I've defined a word that takes a long like this:

const PROGMEM char ble_begin_str[] = "ble_begin";
// ( long -- )
// set the data rate for the SoftwareSerial port
static void _ble_begin(void) {
  mySerial.begin((long) pop());
}

But when executed, I get:

> > ble_begin 19200

ble_begin EXCEPTION(-4): Stack Underflow

Any suggestions?

**Comment by sdwood68** [comment]
My gut feeling is that the 19200 is not being interpreted as a long, and is
being pushed into the stack as a standard cell.

Stuart.

**Comment by sdwood68** [comment]
Dennis,

Try entering "19200 ble_begin"

remember the parameter most be entered first and than the opreand.

I initially miss read your post thinking that you were trying to enter
doubles. and was thinking that it was because I've not implemnted the
double word set.

Stuart

**Comment by DRuffer** [comment]
Well duh! Sorry for my lapse in RPN.

Thanks

DaR
