### ISSUE TITLE
For beginner

### ISSUE THREAD

**Issue by amoskovskij** [sdwood68/YAFFA#5]
Hello!
How can I use YAFFA.
Describe for the beginner.

**Comment by amoskovskij** [comment]
It seems so:

I. Put all files in to directory YAFFA

II. In Arduino IDE open file YAFFA.ino

III. Upload sketch.

IV. Open a linux terminal window.

V. Enter the following command:

stty -F /dev/ttyACM0 cs8 19200 ignbrk -brkint -imaxbel -opost -onlcr -isig -icanon -iexten -echo -echoe -echok -echoctl -echoke noflsh -ixon -crtscts

where ttyACM0 - is your Arduino UNO.

VI. Start screen by typing the following:

screen /dev/ttyACM0 19200

VII. Use YAFFA.

VIII. To kill a screen session:

CTRL+a and then 'k'

**Comment by sdwood68** [comment]
Hi,

The one thing to remember is that you need to send a carriage return at the
end of your text input for the interpreter to process the string. You can
use the terminal built into the Arduino IDE, just remember to set it to
send the carriage return.

I hope you have it working!

Stuart
