### ISSUE TITLE
Arduino Mega 2560

### ISSUE THREAD

**Issue by amoskovskij** [sdwood68/YAFFA#6]
Hi !
What do I need to change in the source code to use Arduino Mega 2560 ?

I copy section
# if defined(**AVR_ATmega328P**) // Arduino Uno

to empty section
# elif defined(**AVR_ATmega1280**) || defined(**AVR_ATmega2560**)  // Mega 1280 & 2560

YAFFA work OK.
Do I need something else ?

**Comment by sdwood68** [comment]
You will want to re-size the definitions for the for the amount of RAM you
have.
I might have time in the next day to take a look and try and mock up
something for you to try if you are having trouble.

Stuart

**Comment by sdwood68** [comment]
Try this in the YAFFA.h file. and let me know if you have any problems,
Stuart

#if defined(**AVR_ATmega328P**) // Arduino Uno
  static const unsigned long EPROM_SIZE = 1;
  static const unsigned long SRAM_SIZE = 2;
  #define PROC_STR "ATmega328P"
  #define HOLD_SIZE     31
  #define PAD_SIZE      96
  #define RSTACK_SIZE   16
  #define STACK_SIZE    16
  #define BUFFER_SIZE   96
  #define WORD_SIZE     32

#elif defined(**AVR_ATmega1280**) || defined(**AVR_ATmega2560**)  // Mega 1280 & 2560
  static const unsigned long EPROM_SIZE = 4;
  static const unsigned long SRAM_SIZE = 8;
  #define PROC_STR "ATmega1280"
  #define HOLD_SIZE     31
  #define PAD_SIZE      127
  #define RSTACK_SIZE   32
  #define STACK_SIZE    32
  #define BUFFER_SIZE   127
  #define WORD_SIZE     32

#elif defined(**AVR_ATmega32U4**) // Arduino Leonardo
  static const unsigned long EPROM_SIZE = 1;
  static const unsigned long SRAM_SIZE = 2.5;
  #define PROC_STR "ATmega32U4"
  #define HOLD_SIZE     31
  #define PAD_SIZE      96
  #define RSTACK_SIZE   16
  #define STACK_SIZE    16
  #define BUFFER_SIZE   96
  #define WORD_SIZE     32

#endif

static const unsigned long FORTH_SIZE    ((SRAM_SIZE_1024_2)/(sizeof(cell_t)*3));

**Comment by amoskovskij** [comment]
I did so:

//  #define EPROM_SIZE = 4;
//  #define SRAM_SIZE = 8;
//  #define PROC_STR "ATmega2560"
  #define STRING_SIZE   128
  #define HOLD_SIZE   32
//  #define PAD_SIZE 127
  #define RSTACK_SIZE   32
  #define STACK_SIZE    32
  #define BUFFER_SIZE   96
  #define WORD_SIZE   32
  #define FORTH_SIZE    7*1024+256

Work OK.

That's right I understand that for FORTH_SIZE necessary to select the maximum numeric value?
