### ISSUE TITLE
 I want to help your project

### ISSUE THREAD

**Issue by amoskovskij** [sdwood68/YAFFA#7]
I'm not very advanced user Arduino, C and Forth.
But I want to help popularization and development of your project.
What help can I give you?
Maybe the documentation or testing?

**Comment by sdwood68** [comment]
Slogger3d,

The best way to help is to test things out and report any problems you find.
Please you the issues area for bugs that you find. if tou have general
questions please email me directly at swood@rochester.rr.com.

If you not sure where to start there are a couple of books on line with
lots of examples that you can test out on YAFFA.

http://thebeez.home.xs4all.nl/ForthPrimer/Forth_primer.html
http://www.forth.com/starting-forth/index.html
http://thinking-forth.sourceforge.net/

Thanks!

Stuart
