### ISSUE TITLE
fatal error: MemoryFree.h: No such file or directory

### ISSUE THREAD

**Issue by DRuffer** [sdwood68/YAFFA#8]
I had to add https://github.com/sudar/MemoryFree/archive/master.zip
But still getting:
C:\Users\druff\Documents\Arduino\YAFFA\Dictionary.ino: In function 'void setup()':
Dictionary:281: error: 'freeMemory' was not declared in this scope
       _throw();
                    ^
exit status 1
'freeMemory' was not declared in this scope

**Comment by sdwood68** [comment]
Thank you for the response. I will look into it as soon as I can.

Are you using YAFFA for the atmega's or for the 32 bit ARM versions?

Stuart

**Comment by DRuffer** [comment]
I’m using the Adafruit Pro Trinket 5V which I believe has a ATMEGA328P.

DaR

**Comment by sdwood68** [comment]
Dennis,

Please use this library for Free Memory
#include <MemoryFree.h>  // https://github.com/McNeight/MemoryFree
I updated to code to document the prober library.

Stuart

**Comment by DRuffer** [comment]
Sorry it took so long to get back to you, but using this other library works fine now:

YAFFA - Yet Another Forth For Arduino, Version 0.6

Thanks

DaR

**Comment by cashiecoder** [comment]
To set up MemoryFree, go to https://github.com/mpflaga/Arduino-MemoryFree and click the "Download Zip". Now go into the Arduino IDE and goto Sketch > Include Library > Add .ZIP library. Now browse to the file you downloaded and select it. Now, MemoryFree will be installed as a library and can be used by YAFFA.
